#!/bin/bash
set -eo pipefail

# Checking for DB liveness before continuing with DB set up.
count=0
while [ $count -lt 40 ]; do
  if [[ $(mysql -h$CLUEBRINGER_DB_HOST -uroot -p$MYSQL_ROOT_PASSWORD -e "select 1" &>/dev/null ; echo $?) -ne 0 ]]; then
    echo "Waiting for DB to be ready."
    sleep 3
    let count+=1
  else
    echo "DB appears to be ready."
    break
  fi
done
# Die if DB doesn't come up in time.
if [ $count -eq 40 ]; then
  echo "!!!WARNING!!! DB didn't come up in time."
  exit 0
fi

# Set up DB if it's empty.
if [[ $(mysql -N -h$CLUEBRINGER_DB_HOST -uroot -p$MYSQL_ROOT_PASSWORD -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '$MYSQL_DATABASE';") == 0 ]]; then
  echo "Setting up cluebringer DB."
  mysql -h$CLUEBRINGER_DB_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /tmp/policyd-db.mysql
else
  echo "Cluebringer DB not empty, exiting."
  exit 0
fi
